server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lecaru_db
    username: lecaru
    password: lecaru
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    database:
      database-plataform:  org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  